import { format_currency } from "@/components/recovery-summary/recoverySummaryFormatters";

export function get_warning_detail(warning_key, values = {}) {
  const {
    margin_pool,
    total_cost_burden,
    net_position,
    current_margin_per_driver,
    required_recovery_per_driver,
    recovery_gap_per_driver,
    total_revenue,
    total_direct_costs,
  } = values;

  const detail_map = {
    negative_net_position: {
      title: "Margin pool is below total cost burden",
      meaning:
        "Business Summary is showing that the margin pool generated by the business is not enough to cover the total cost burden.",
      source:
        "This comes from Business Summary: margin pool is compared against total cost burden. Use Business Summary Macro Position to audit the source values.",
      calculation_title: "Net Position calculation",
      actual_maths: [
        {
          label: "Margin Pool",
          value: format_currency(margin_pool),
        },
        {
          label: "Total Cost Burden",
          value: format_currency(total_cost_burden),
        },
        {
          label: "Net Position",
          value: format_currency(net_position),
          emphasis: true,
        },
      ],
      formula: "Margin Pool - Total Cost Burden = Net Position",
    },

    recovery_gap_negative: {
      title: "Required recovery level is not being met",
      meaning:
        "The business is not currently generating enough margin to meet the recovery level required by the current model.",
      source:
        "This comes from Business Summary: current margin is compared against required recovery.",
      calculation_title: "Recovery Gap calculation",
      actual_maths: [
        {
          label: "Current Margin",
          value: format_currency(current_margin_per_driver),
        },
        {
          label: "Required Recovery",
          value: format_currency(required_recovery_per_driver),
        },
        {
          label: "Recovery Gap",
          value: format_currency(recovery_gap_per_driver),
          emphasis: true,
        },
      ],
      formula: "Current Margin - Required Recovery = Recovery Gap",
    },

    negative_margin_pool: {
      title: "Direct costs are higher than revenue",
      meaning:
        "The business is currently showing a negative margin pool before the operating cost burden is recovered.",
      source:
        "This comes from Revenue / COGS. Use Business Summary Macro Position to audit revenue, direct costs, and margin pool source values.",
      calculation_title: "Margin Pool calculation",
      actual_maths: [
        {
          label: "Revenue",
          value: format_currency(total_revenue),
        },
        {
          label: "Direct Costs",
          value: format_currency(total_direct_costs),
        },
        {
          label: "Margin Pool",
          value: format_currency(margin_pool),
          emphasis: true,
        },
      ],
      formula: "Revenue - Direct Costs = Margin Pool",
    },

    share_not_balanced: {
      title: "Recovery split does not total 100%",
      meaning:
        "The recovery burden cannot be assigned correctly until the labour, asset, and absorbed overhead shares total 100%.",
      source: "This comes from Recovery Summary recovery split inputs.",
      calculation_title: "Recovery Split rule",
      actual_maths: [],
      formula: "Labour Share + Asset Share + Absorbed Overhead Share = 100%",
    },

    business_summary_not_ready: {
      title: "Business Summary is not ready",
      meaning:
        "Recovery Summary is waiting for a usable Business Summary result before it can produce a reliable recovery model.",
      source: "This comes from the Business Summary readiness state.",
      calculation_title: "Business Summary readiness",
      actual_maths: [],
      formula: "Business Summary Ready = true",
    },

    upstream_model_not_ready: {
      title: "Upstream model is not trusted",
      meaning:
        "The model has upstream readiness issues, so the recovery model should not be treated as final.",
      source: "This comes from Model Readiness.",
      calculation_title: "Model Readiness rule",
      actual_maths: [],
      formula: "Model Readiness = ready or warning",
    },

    no_activity_driver: {
      title: "No recovery driver is available",
      meaning:
        "The system does not yet have a valid activity base to spread the cost burden across.",
      source:
        "This comes from Business Summary and Business Setup through the selected activity driver.",
      calculation_title: "Recovery Driver rule",
      actual_maths: [],
      formula: "Total Cost Burden ÷ Activity Driver = Required Recovery",
    },

    no_required_recovery_per_driver: {
      title: "Required recovery level is missing",
      meaning:
        "The system cannot calculate the required recovery level for the selected driver.",
      source: "This comes from Business Summary.",
      calculation_title: "Required Recovery calculation",
      actual_maths: [],
      formula: "Required Recovery = Total Cost Burden ÷ Activity Driver",
    },

    no_productive_output: {
      title: "No productive output is available",
      meaning:
        "Labour-driven recovery cannot be calculated without productive output or recovery hours.",
      source: "This comes from Labour / Cost Summary.",
      calculation_title: "Recovery Hours rule",
      actual_maths: [],
      formula: "Required Recovery Per Hour = Total Cost Burden ÷ Recovery Hours",
    },

    no_units_sold: {
      title: "No units sold value is available",
      meaning:
        "Product-driven recovery cannot be calculated without annual units sold.",
      source: "This comes from Revenue / COGS in product-based mode.",
      calculation_title: "Units Sold rule",
      actual_maths: [],
      formula: "Required Recovery Per Unit = Total Cost Burden ÷ Units Sold",
    },

    asset_share_without_asset_recovery_base: {
      title: "Asset recovery has no asset base",
      meaning:
        "The recovery split assigns burden to assets, but there is no usable asset recovery base available.",
      source: "This comes from Recovery Summary and Assets.",
      calculation_title: "Asset Recovery calculation",
      actual_maths: [],
      formula: "Asset Recovery Cost = Total Cost Burden × Asset Share",
    },

    labour_share_without_productive_output: {
      title: "Labour recovery has no labour base",
      meaning:
        "The recovery split assigns burden to labour, but there is no usable recovery-hour base available.",
      source: "This comes from Recovery Summary and Labour / Cost Summary.",
      calculation_title: "Labour Recovery calculation",
      actual_maths: [],
      formula: "Labour Recovery Rate = Labour Recovery Cost ÷ Recovery Hours",
    },
  };

  return (
    detail_map[warning_key] || {
      title: "Recovery note",
      meaning:
        "This note is attached to the current recovery model and should be reviewed.",
      source: "Source not specified.",
      calculation_title: "Recovery note",
      actual_maths: [],
      formula: "No formula available.",
    }
  );
}
