import { format_currency } from "@/components/recovery-summary/recoverySummaryFormatters";

export function get_warning_detail(warning_key, values = {}) {
  const {
    margin_pool,
    total_cost_burden,
    net_position,
    current_margin_per_driver,
    required_recovery_per_driver,
    recovery_gap_per_driver,
    total_revenue,
    total_direct_costs,
  } = values;

  const detail_map = {
    negative_net_position: {
      title: "Margin pool is below total cost burden",
      meaning:
        "Business Summary is showing that the margin pool generated by the business is not enough to cover the total cost burden.",
      source:
        "Use Business Summary Macro Position to audit revenue, direct costs, people cost, asset cost, and business overheads.",
      calculation_title: "Carry-forward position",
      actual_maths: [
        {
          label: "Margin Pool",
          value: format_currency(margin_pool),
        },
        {
          label: "Total Cost Burden",
          value: format_currency(total_cost_burden),
        },
        {
          label: "Net Position",
          value: format_currency(net_position),
          emphasis: true,
        },
      ],
      formula: "Margin Pool - Total Cost Burden = Net Position",
    },

    recovery_gap_negative: {
      title: "Required recovery level is not being met",
      meaning:
        "Business Summary is showing that current margin is below the required recovery level for the selected driver.",
      source:
        "Use Business Summary to audit the current margin, required recovery, and recovery gap. Recovery Summary carries this pressure forward.",
      calculation_title: "Carry-forward recovery pressure",
      actual_maths: [
        {
          label: "Current Margin",
          value: format_currency(current_margin_per_driver),
        },
        {
          label: "Required Recovery",
          value: format_currency(required_recovery_per_driver),
        },
        {
          label: "Recovery Gap",
          value: format_currency(recovery_gap_per_driver),
          emphasis: true,
        },
      ],
      formula: "Current Margin - Required Recovery = Recovery Gap",
    },

    negative_margin_pool: {
      title: "Direct costs are higher than revenue",
      meaning:
        "Business Summary is showing a negative margin pool before the operating cost burden is recovered.",
      source:
        "Use Business Summary Macro Position to audit revenue, direct costs, and margin pool source values.",
      calculation_title: "Carry-forward margin position",
      actual_maths: [
        {
          label: "Revenue",
          value: format_currency(total_revenue),
        },
        {
          label: "Direct Costs",
          value: format_currency(total_direct_costs),
        },
        {
          label: "Margin Pool",
          value: format_currency(margin_pool),
          emphasis: true,
        },
      ],
      formula: "Revenue - Direct Costs = Margin Pool",
    },

    share_not_balanced: {
      title: "Recovery split does not total 100%",
      meaning:
        "The recovery burden cannot be assigned correctly until the labour, asset, and absorbed overhead shares total 100%.",
      source:
        "Review the Recovery Summary recovery split inputs before carrying this strategy forward.",
      calculation_title: "Recovery split rule",
      actual_maths: [],
      formula: "Labour Share + Asset Share + Absorbed Overhead Share = 100%",
    },

    business_summary_not_ready: {
      title: "Business Summary is not ready",
      meaning:
        "Recovery Summary is waiting for a usable Business Summary result before it can produce a reliable recovery strategy.",
      source:
        "Review Business Summary first. Recovery Summary depends on the Business Summary result.",
      calculation_title: "Business Summary readiness",
      actual_maths: [],
      formula: "Business Summary Ready = true",
    },

    upstream_model_not_ready: {
      title: "Upstream model is not trusted",
      meaning:
        "The model has upstream readiness issues, so the recovery strategy should not be treated as final.",
      source:
        "Review Model Readiness and the upstream setup pages before using this result.",
      calculation_title: "Model readiness rule",
      actual_maths: [],
      formula: "Model Readiness = ready or warning",
    },

    no_activity_driver: {
      title: "No recovery driver is available",
      meaning:
        "The system does not yet have a valid activity base to express the recovery burden.",
      source:
        "Review Business Setup and Business Summary. Labour-driven models need recovery hours. Product-driven models need units sold.",
      calculation_title: "Recovery driver rule",
      actual_maths: [],
      formula: "Total Cost Burden ÷ Activity Driver = Required Recovery",
    },

    no_required_recovery_per_driver: {
      title: "Required recovery level is missing",
      meaning:
        "The system cannot calculate the required recovery level for the selected driver.",
      source:
        "Review Business Summary. Recovery Summary needs a required recovery value before it can carry the strategy forward.",
      calculation_title: "Required recovery rule",
      actual_maths: [],
      formula: "Required Recovery = Total Cost Burden ÷ Activity Driver",
    },

    no_productive_output: {
      title: "No productive output is available",
      meaning:
        "Labour-driven recovery cannot be expressed without productive output or recovery hours.",
      source:
        "Review Labour and Cost Summary. Recovery Summary needs a recovery-hour base before Cost Allocation can test the strategy.",
      calculation_title: "Recovery hours rule",
      actual_maths: [],
      formula: "Required Recovery Per Hour = Total Cost Burden ÷ Recovery Hours",
    },

    no_units_sold: {
      title: "No units sold value is available",
      meaning:
        "Product-driven recovery cannot be expressed without annual units sold.",
      source:
        "Review Revenue / COGS and Business Summary in product-driven mode.",
      calculation_title: "Units sold rule",
      actual_maths: [],
      formula: "Required Recovery Per Unit = Total Cost Burden ÷ Units Sold",
    },

    asset_share_without_asset_recovery_base: {
      title: "Asset recovery has no asset base",
      meaning:
        "The recovery split assigns burden to assets, but there is no usable asset recovery base available.",
      source:
        "Review Assets before carrying an asset-supported recovery strategy into Cost Allocation.",
      calculation_title: "Asset recovery rule",
      actual_maths: [],
      formula: "Asset Recovery Cost = Total Cost Burden × Asset Share",
    },

    labour_share_without_productive_output: {
      title: "Labour recovery has no labour base",
      meaning:
        "The recovery split assigns burden to labour, but there is no usable recovery-hour base available.",
      source:
        "Review Labour and Cost Summary before carrying a labour-led recovery strategy into Cost Allocation.",
      calculation_title: "Labour recovery rule",
      actual_maths: [],
      formula: "Labour Recovery Rate = Labour Recovery Cost ÷ Recovery Hours",
    },
  };

  return (
    detail_map[warning_key] || {
      title: "Recovery note",
      meaning:
        "This note is attached to the current recovery strategy and should be reviewed.",
      source:
        "Review Business Summary for source values, then use Recovery Summary to carry the strategy forward.",
      calculation_title: "Recovery note",
      actual_maths: [],
      formula: "No formula available.",
    }
  );
}