// Mirra v5.0 - Calculation Trace Pilot Map
// Generated from S03_CALCULATION_TRACE_PILOT_LINEAGE_MAP_v5.0.txt
// Read-only supporting data. Do not calculate from this file.

export const traceNodes = [
  {
    node_id: "business_summary.required_recovery_per_driver",
    module_name: "business-summary",
    variable_name: "required_recovery_per_driver",
    display_label: "Required Recovery Per Driver",
    value_source: "output_contract",
    formula_text: "required_recovery_per_driver = total_cost_burden / activity_driver_value",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/businessSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "business_summary.total_cost_burden",
    module_name: "business-summary",
    variable_name: "total_cost_burden",
    display_label: "Total Cost Burden",
    value_source: "output_contract",
    formula_text: "Business Summary receives total_cost_burden from Cost Summary; Cost Summary owns cost burden aggregation",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/businessSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "business_summary.activity_driver_value",
    module_name: "business-summary",
    variable_name: "activity_driver_value",
    display_label: "Activity Driver Value",
    value_source: "output_contract",
    formula_text: "If business_type = labour_based, activity_driver_value = total_productive_output; if business_type = product_based, activity_driver_value = total_derived_units_annual or units_sold_annual",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/businessSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "business_summary.total_productive_output",
    module_name: "business-summary",
    variable_name: "total_productive_output",
    display_label: "Total Productive Output",
    value_source: "output_contract",
    formula_text: "Business Summary consumes total_productive_output from Cost Summary; labour-based activity_driver_value = total_productive_output",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "business_summary.total_derived_units_annual",
    module_name: "business-summary",
    variable_name: "total_derived_units_annual",
    display_label: "Total Derived Units Annual",
    value_source: "output_contract",
    formula_text: "Business Summary consumes total_derived_units_annual from Revenue / COGS; product-based activity_driver_value = total_derived_units_annual or units_sold_annual",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "business_summary.units_sold_annual",
    module_name: "business-summary",
    variable_name: "units_sold_annual",
    display_label: "Units Sold Annual",
    value_source: "output_contract",
    formula_text: "Accepted Business Summary output contract field; product-based activity_driver_value may use units_sold_annual where total_derived_units_annual is not the selected annual unit driver",
    is_root_input: false,
    brief_reference: "14_MIRRA_BUSINESS_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "revenue_cogs.unit_driver_rows",
    module_name: "revenue-cogs",
    variable_name: "unit_driver_rows",
    display_label: "Revenue / COGS Unit Driver Rows",
    value_source: "raw_source_import",
    formula_text: "Product/unit mode root setup rows; each row includes unit_label, unit_type, annual_revenue, average_sale_rate_per_unit, estimated_units_annual, derived_units_annual, annual_margin_pool, and margin_per_unit. estimated_units_annual may be user-entered; derived_units_annual may be calculated from revenue / average sale rate. Do not invent annual units.",
    is_root_input: true,
    brief_reference: "13_MIRRA_REVENUE_COGS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "revenue_cogs.total_derived_units_annual",
    module_name: "revenue-cogs",
    variable_name: "total_derived_units_annual",
    display_label: "Revenue / COGS Total Derived Units Annual",
    value_source: "output_contract",
    formula_text: "total_derived_units_annual = sum derived_units_annual from unit_driver_rows where product/unit mode requires trusted unit recovery",
    is_root_input: false,
    brief_reference: "13_MIRRA_REVENUE_COGS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "revenue_cogs.units_sold_annual",
    module_name: "revenue-cogs",
    variable_name: "units_sold_annual",
    display_label: "Revenue / COGS Units Sold Annual",
    value_source: "raw_source_import",
    formula_text: "Legacy compatibility product/unit annual unit field; preferred v4.0 fields are unit_driver_rows and total_derived_units_annual. If both exist, they must not diverge silently.",
    is_root_input: true,
    brief_reference: "13_MIRRA_REVENUE_COGS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "cost_summary.total_cost_burden",
    module_name: "cost-summary",
    variable_name: "total_cost_burden",
    display_label: "Total Cost Burden",
    value_source: "output_contract",
    formula_text: "total_cost_burden = total_people_cost_annual + total_asset_cost_annual + total_business_overheads",
    is_root_input: false,
    brief_reference: "06_MIRRA_COST_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/costSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "cost_summary.total_people_cost_annual",
    module_name: "cost-summary",
    variable_name: "total_people_cost_annual",
    display_label: "Total People Cost Annual",
    value_source: "output_contract",
    formula_text: "Labour source output consumed by Cost Summary",
    is_root_input: false,
    brief_reference: "06_MIRRA_COST_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/costSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "cost_summary.total_asset_cost_annual",
    module_name: "cost-summary",
    variable_name: "total_asset_cost_annual",
    display_label: "Total Asset Cost Annual",
    value_source: "output_contract",
    formula_text: "Assets source output consumed by Cost Summary",
    is_root_input: false,
    brief_reference: "06_MIRRA_COST_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/costSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "cost_summary.total_business_overheads",
    module_name: "cost-summary",
    variable_name: "total_business_overheads",
    display_label: "Total Business Overheads",
    value_source: "output_contract",
    formula_text: "General Overheads source output consumed by Cost Summary",
    is_root_input: false,
    brief_reference: "06_MIRRA_COST_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/costSummaryCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "cost_summary.total_productive_output",
    module_name: "cost-summary",
    variable_name: "total_productive_output",
    display_label: "Total Productive Output",
    value_source: "output_contract",
    formula_text: "Cost Summary consumes total_productive_output from Labour and passes it downstream; Cost Summary does not own product/unit output",
    is_root_input: false,
    brief_reference: "06_MIRRA_COST_SUMMARY_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.total_people_cost_annual",
    module_name: "labour",
    variable_name: "total_people_cost_annual",
    display_label: "Total People Cost Annual",
    value_source: "output_contract",
    formula_text: "total_people_cost_annual = total_labour_cost_annual",
    is_root_input: false,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/selectors/labour/labourOutputContractSelectors.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.total_productive_output",
    module_name: "labour",
    variable_name: "total_productive_output",
    display_label: "Total Productive Output",
    value_source: "output_contract",
    formula_text: "Labour source output for total productive labour hours / productive output consumed by Cost Summary and Business Summary",
    is_root_input: false,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.total_labour_cost_annual",
    module_name: "labour",
    variable_name: "total_labour_cost_annual",
    display_label: "Total Labour Cost Annual",
    value_source: "output_contract",
    formula_text: "total_labour_cost_annual = sum annual_labour_cost for active staff",
    is_root_input: false,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.annual_labour_cost",
    module_name: "labour",
    variable_name: "annual_labour_cost",
    display_label: "Annual Labour Cost",
    value_source: "output_contract",
    formula_text: "annual_labour_cost = annual_base_cost + annual_on_costs",
    is_root_input: false,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.annual_base_cost",
    module_name: "labour",
    variable_name: "annual_base_cost",
    display_label: "Annual Base Cost",
    value_source: "raw_source_import",
    formula_text: "Direct Labour staff-row input; Labour must not use P&L labour as operational source truth",
    is_root_input: true,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "labour.annual_on_costs",
    module_name: "labour",
    variable_name: "annual_on_costs",
    display_label: "Annual On-Costs",
    value_source: "raw_source_import",
    formula_text: "Direct Labour staff-row input for employer contributions, payroll on-costs, leave allowance, ACC / workers compensation, KiwiSaver / superannuation employer cost, and payroll tax where relevant",
    is_root_input: true,
    brief_reference: "07_MIRRA_LABOUR_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.total_asset_cost_annual",
    module_name: "assets",
    variable_name: "total_asset_cost_annual",
    display_label: "Total Asset Cost Annual",
    value_source: "output_contract",
    formula_text: "total_asset_cost_annual = sum total_asset_cost_annual for active assets",
    is_root_input: false,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_total_asset_cost_annual",
    module_name: "assets",
    variable_name: "total_asset_cost_annual",
    display_label: "Per Asset Total Asset Cost Annual",
    value_source: "output_contract",
    formula_text: "total_asset_cost_annual = asset_ownership_cost_annual + asset_finance_interest_annual + asset_lease_cost_annual + asset_depreciation_or_replacement_cost_annual + asset_insurance_cost_annual + asset_registration_cost_annual + asset_other_ownership_cost_annual + assigned_running_cost_transfers_annual",
    is_root_input: false,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "hooks/useAssets.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_ownership_cost_annual",
    module_name: "assets",
    variable_name: "asset_ownership_cost_annual",
    display_label: "Asset Ownership Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for asset ownership cost",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_finance_interest_annual",
    module_name: "assets",
    variable_name: "asset_finance_interest_annual",
    display_label: "Asset Finance Interest Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for finance interest; principal must not be included",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_lease_cost_annual",
    module_name: "assets",
    variable_name: "asset_lease_cost_annual",
    display_label: "Asset Lease Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for lease cost where applicable",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_depreciation_or_replacement_cost_annual",
    module_name: "assets",
    variable_name: "asset_depreciation_or_replacement_cost_annual",
    display_label: "Asset Depreciation Or Replacement Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for depreciation / replacement allowance where enabled",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_insurance_cost_annual",
    module_name: "assets",
    variable_name: "asset_insurance_cost_annual",
    display_label: "Asset Insurance Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for asset insurance where explicitly treated as asset-owned",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_registration_cost_annual",
    module_name: "assets",
    variable_name: "asset_registration_cost_annual",
    display_label: "Asset Registration Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for registration where explicitly treated as asset-owned",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_other_ownership_cost_annual",
    module_name: "assets",
    variable_name: "asset_other_ownership_cost_annual",
    display_label: "Asset Other Ownership Cost Annual",
    value_source: "raw_source_import",
    formula_text: "Direct Assets asset-row input for other fixed ownership costs",
    is_root_input: true,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.general_overheads_pool_amount",
    module_name: "general-overheads",
    variable_name: "general_overheads_pool_amount",
    display_label: "General Overheads Pool Amount",
    value_source: "output_contract",
    formula_text: "general_overheads_pool_amount = total_general_overheads by default; General Overheads owns the original overhead source pool",
    is_root_input: false,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.asset_running_cost_transfers",
    module_name: "assets",
    variable_name: "asset_running_cost_transfers",
    display_label: "Asset Running Cost Transfers",
    value_source: "output_contract",
    formula_text: "asset_running_cost_transfers[] rows explicitly transfer portions of asset-related source pools into productive assets; each transfer must preserve source pool, assigned amount, remaining pool, over-allocated amount, and allocation status",
    is_root_input: false,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.total_asset_running_cost_transferred",
    module_name: "assets",
    variable_name: "total_asset_running_cost_transferred",
    display_label: "Total Asset Running Cost Transferred",
    value_source: "output_contract",
    formula_text: "total_asset_running_cost_transferred = sum assigned productive-asset running cost transfer amounts from asset_running_cost_transfers[]",
    is_root_input: false,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "assets.assigned_running_cost_transfers_annual",
    module_name: "assets",
    variable_name: "assigned_running_cost_transfers_annual",
    display_label: "Assigned Running Cost Transfers Annual",
    value_source: "output_contract",
    formula_text: "assigned_running_cost_transfers_annual = transferred productive asset running cost portion assigned from explicit asset_running_cost_transfers[] source-pool rows; General Overheads remains owner of the original overhead source pool",
    is_root_input: false,
    brief_reference: "09_MIRRA_ASSETS_MODULE_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.gross_general_overheads_benchmark",
    module_name: "general-overheads",
    variable_name: "gross_general_overheads_benchmark",
    display_label: "Gross General Overheads Benchmark",
    value_source: "raw_source_import",
    formula_text: "P&L / general overhead benchmark before exclusions",
    is_root_input: true,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.asset_finance_interest_excluded",
    module_name: "general-overheads",
    variable_name: "asset_finance_interest_excluded",
    display_label: "Asset Finance Interest Excluded",
    value_source: "raw_source_import",
    formula_text: "Explicit user/module selection flag where asset finance interest is selected as asset-related and reviewed through the Assets pathway; exclusion must be visible and must not delete the original P&L line",
    is_root_input: true,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.asset_finance_interest_excluded_amount",
    module_name: "general-overheads",
    variable_name: "asset_finance_interest_excluded_amount",
    display_label: "Asset Finance Interest Excluded Amount",
    value_source: "raw_source_import",
    formula_text: "Explicit amount excluded from General Overheads when asset finance interest is selected as asset-related; excluded amount must remain visible for Module Reconciliation and must prevent double counting",
    is_root_input: true,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.adjusted_general_overheads_benchmark",
    module_name: "general-overheads",
    variable_name: "adjusted_general_overheads_benchmark",
    display_label: "Adjusted General Overheads Benchmark",
    value_source: "output_contract",
    formula_text: "adjusted_general_overheads_benchmark = gross_general_overheads_benchmark - asset_finance_interest_excluded_amount",
    is_root_input: false,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.net_general_overheads",
    module_name: "general-overheads",
    variable_name: "net_general_overheads",
    display_label: "Net General Overheads",
    value_source: "output_contract",
    formula_text: "net_general_overheads = overhead total after valid exclusions",
    is_root_input: false,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.total_general_overheads",
    module_name: "general-overheads",
    variable_name: "total_general_overheads",
    display_label: "Total General Overheads",
    value_source: "output_contract",
    formula_text: "total_general_overheads = sum of active general_overhead_categories annual_amount after exclusions and adjustments defined in this module",
    is_root_input: false,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: "lib/calculations/generalOverheadCalculations.js",
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.general_overhead_categories",
    module_name: "general-overheads",
    variable_name: "general_overhead_categories",
    display_label: "General Overhead Categories",
    value_source: "raw_source_import",
    formula_text: "Root source category container fed by P&L operating expense classifications, manual overhead entries, saved overhead categories, imported operating expense lines, future Xero API import, or future database-backed profile records; each category annual_amount feeds total_general_overheads after exclusions and adjustments",
    is_root_input: true,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
  {
    node_id: "general_overheads.total_business_overheads",
    module_name: "general-overheads",
    variable_name: "total_business_overheads",
    display_label: "Total Business Overheads",
    value_source: "output_contract",
    formula_text: "Cost Summary uses total_general_overheads as total_business_overheads",
    is_root_input: false,
    brief_reference: "05_MIRRA_GENERAL_OVERHEADS_v4.0_LOCKED.txt",
    last_verified_against: "v5.0 pilot draft",
    source_file: null,
    implementation_status: "verified_in_brief",
    notes: "",
  },
];
