// Mirra v5.0 - Calculation Trace Pilot Map
// Generated from S03_CALCULATION_TRACE_PILOT_LINEAGE_MAP_v5.0.txt
// Read-only supporting data. Do not calculate from this file.

export const traceEdges = [
  {
    edge_id: "cost_summary.total_cost_burden__to__business_summary.total_cost_burden",
    from_node_id: "cost_summary.total_cost_burden",
    to_node_id: "business_summary.total_cost_burden",
    relationship_type: "direct_input",
    notes: "Business Summary receives total_cost_burden from Cost Summary output_contract.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "business_summary.total_cost_burden__to__business_summary.required_recovery_per_driver",
    from_node_id: "business_summary.total_cost_burden",
    to_node_id: "business_summary.required_recovery_per_driver",
    relationship_type: "direct_input",
    notes: "Verified from formula: required_recovery_per_driver = total_cost_burden / activity_driver_value",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "business_summary.activity_driver_value__to__business_summary.required_recovery_per_driver",
    from_node_id: "business_summary.activity_driver_value",
    to_node_id: "business_summary.required_recovery_per_driver",
    relationship_type: "direct_input",
    notes: "Verified from formula: required_recovery_per_driver = total_cost_burden / activity_driver_value",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "cost_summary.total_productive_output__to__business_summary.total_productive_output",
    from_node_id: "cost_summary.total_productive_output",
    to_node_id: "business_summary.total_productive_output",
    relationship_type: "direct_input",
    notes: "Business Summary consumes total_productive_output from Cost Summary for labour-based activity driver.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "business_summary.total_productive_output__to__business_summary.activity_driver_value",
    from_node_id: "business_summary.total_productive_output",
    to_node_id: "business_summary.activity_driver_value",
    relationship_type: "conditional_input",
    notes: "If business_type = labour_based, activity_driver_value = total_productive_output.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "revenue_cogs.unit_driver_rows__to__revenue_cogs.total_derived_units_annual",
    from_node_id: "revenue_cogs.unit_driver_rows",
    to_node_id: "revenue_cogs.total_derived_units_annual",
    relationship_type: "sum_component",
    notes: "Revenue / COGS formula source: total_derived_units_annual is derived from unit_driver_rows annual unit setup. estimated_units_annual may be user-entered; derived_units_annual may be calculated from revenue / average sale rate.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "revenue_cogs.total_derived_units_annual__to__business_summary.total_derived_units_annual",
    from_node_id: "revenue_cogs.total_derived_units_annual",
    to_node_id: "business_summary.total_derived_units_annual",
    relationship_type: "direct_input",
    notes: "Business Summary consumes total_derived_units_annual from Revenue / COGS for product/unit mode.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "revenue_cogs.units_sold_annual__to__business_summary.units_sold_annual",
    from_node_id: "revenue_cogs.units_sold_annual",
    to_node_id: "business_summary.units_sold_annual",
    relationship_type: "direct_input",
    notes: "Business Summary may consume units_sold_annual where selected as the product/unit annual unit driver.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "business_summary.total_derived_units_annual__to__business_summary.activity_driver_value",
    from_node_id: "business_summary.total_derived_units_annual",
    to_node_id: "business_summary.activity_driver_value",
    relationship_type: "conditional_input",
    notes: "If business_type = product_based, activity_driver_value = total_derived_units_annual or units_sold_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "business_summary.units_sold_annual__to__business_summary.activity_driver_value",
    from_node_id: "business_summary.units_sold_annual",
    to_node_id: "business_summary.activity_driver_value",
    relationship_type: "conditional_input",
    notes: "If business_type = product_based, activity_driver_value may use units_sold_annual where it is the selected annual unit driver.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "cost_summary.total_people_cost_annual__to__cost_summary.total_cost_burden",
    from_node_id: "cost_summary.total_people_cost_annual",
    to_node_id: "cost_summary.total_cost_burden",
    relationship_type: "sum_component",
    notes: "Verified from formula: total_cost_burden = total_people_cost_annual + total_asset_cost_annual + total_business_overheads",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "cost_summary.total_asset_cost_annual__to__cost_summary.total_cost_burden",
    from_node_id: "cost_summary.total_asset_cost_annual",
    to_node_id: "cost_summary.total_cost_burden",
    relationship_type: "sum_component",
    notes: "Verified from formula: total_cost_burden = total_people_cost_annual + total_asset_cost_annual + total_business_overheads",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "cost_summary.total_business_overheads__to__cost_summary.total_cost_burden",
    from_node_id: "cost_summary.total_business_overheads",
    to_node_id: "cost_summary.total_cost_burden",
    relationship_type: "sum_component",
    notes: "Verified from formula: total_cost_burden = total_people_cost_annual + total_asset_cost_annual + total_business_overheads",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.total_people_cost_annual__to__cost_summary.total_people_cost_annual",
    from_node_id: "labour.total_people_cost_annual",
    to_node_id: "cost_summary.total_people_cost_annual",
    relationship_type: "direct_input",
    notes: "Cost Summary consumes total_people_cost_annual from Labour.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.total_asset_cost_annual__to__cost_summary.total_asset_cost_annual",
    from_node_id: "assets.total_asset_cost_annual",
    to_node_id: "cost_summary.total_asset_cost_annual",
    relationship_type: "direct_input",
    notes: "Cost Summary consumes total_asset_cost_annual from Assets.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.total_business_overheads__to__cost_summary.total_business_overheads",
    from_node_id: "general_overheads.total_business_overheads",
    to_node_id: "cost_summary.total_business_overheads",
    relationship_type: "direct_input",
    notes: "Cost Summary consumes total_business_overheads from General Overheads.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.total_productive_output__to__cost_summary.total_productive_output",
    from_node_id: "labour.total_productive_output",
    to_node_id: "cost_summary.total_productive_output",
    relationship_type: "direct_input",
    notes: "Cost Summary consumes total_productive_output from Labour.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.total_labour_cost_annual__to__labour.total_people_cost_annual",
    from_node_id: "labour.total_labour_cost_annual",
    to_node_id: "labour.total_people_cost_annual",
    relationship_type: "direct_input",
    notes: "Verified from Labour formula: total_people_cost_annual = total_labour_cost_annual",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.annual_labour_cost__to__labour.total_labour_cost_annual",
    from_node_id: "labour.annual_labour_cost",
    to_node_id: "labour.total_labour_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Labour formula: total_labour_cost_annual = sum annual_labour_cost for active staff",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.annual_base_cost__to__labour.annual_labour_cost",
    from_node_id: "labour.annual_base_cost",
    to_node_id: "labour.annual_labour_cost",
    relationship_type: "sum_component",
    notes: "Verified from Labour formula: annual_labour_cost = annual_base_cost + annual_on_costs. annual_base_cost is a direct Labour staff-row input, not P&L source truth.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "labour.annual_on_costs__to__labour.annual_labour_cost",
    from_node_id: "labour.annual_on_costs",
    to_node_id: "labour.annual_labour_cost",
    relationship_type: "sum_component",
    notes: "Verified from Labour formula: annual_labour_cost = annual_base_cost + annual_on_costs. annual_on_costs is a direct Labour staff-row input for direct employment on-costs.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_total_asset_cost_annual__to__assets.total_asset_cost_annual",
    from_node_id: "assets.asset_total_asset_cost_annual",
    to_node_id: "assets.total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula: total_asset_cost_annual = sum total_asset_cost_annual for active assets",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_ownership_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_ownership_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_ownership_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_finance_interest_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_finance_interest_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_finance_interest_annual. Principal must not be included.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_lease_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_lease_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_lease_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_depreciation_or_replacement_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_depreciation_or_replacement_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_depreciation_or_replacement_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_insurance_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_insurance_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_insurance_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_registration_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_registration_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_registration_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_other_ownership_cost_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.asset_other_ownership_cost_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes asset_other_ownership_cost_annual.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.total_general_overheads__to__general_overheads.general_overheads_pool_amount",
    from_node_id: "general_overheads.total_general_overheads",
    to_node_id: "general_overheads.general_overheads_pool_amount",
    relationship_type: "direct_input",
    notes: "General Overheads default source-pool rule: general_overheads_pool_amount = total_general_overheads.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.general_overheads_pool_amount__to__assets.asset_running_cost_transfers",
    from_node_id: "general_overheads.general_overheads_pool_amount",
    to_node_id: "assets.asset_running_cost_transfers",
    relationship_type: "conditional_input",
    notes: "Asset-related running cost source pools may originate in General Overheads; only explicit transferred portions may move into Assets.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.asset_running_cost_transfers__to__assets.total_asset_running_cost_transferred",
    from_node_id: "assets.asset_running_cost_transfers",
    to_node_id: "assets.total_asset_running_cost_transferred",
    relationship_type: "sum_component",
    notes: "total_asset_running_cost_transferred is the sum of assigned productive-asset running cost transfer rows.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.total_asset_running_cost_transferred__to__assets.assigned_running_cost_transfers_annual",
    from_node_id: "assets.total_asset_running_cost_transferred",
    to_node_id: "assets.assigned_running_cost_transfers_annual",
    relationship_type: "direct_input",
    notes: "assigned_running_cost_transfers_annual carries the transferred productive-asset running cost amount into each asset cost calculation.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "assets.assigned_running_cost_transfers_annual__to__assets.asset_total_asset_cost_annual",
    from_node_id: "assets.assigned_running_cost_transfers_annual",
    to_node_id: "assets.asset_total_asset_cost_annual",
    relationship_type: "sum_component",
    notes: "Verified from Assets formula per asset: total_asset_cost_annual includes assigned_running_cost_transfers_annual. This is not a root input; the transfer source path is mapped through general_overheads.general_overheads_pool_amount and assets.asset_running_cost_transfers.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.total_general_overheads__to__general_overheads.total_business_overheads",
    from_node_id: "general_overheads.total_general_overheads",
    to_node_id: "general_overheads.total_business_overheads",
    relationship_type: "direct_input",
    notes: "Verified from General Overheads brief: Cost Summary receives total_general_overheads and uses this as total_business_overheads.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.gross_general_overheads_benchmark__to__general_overheads.adjusted_general_overheads_benchmark",
    from_node_id: "general_overheads.gross_general_overheads_benchmark",
    to_node_id: "general_overheads.adjusted_general_overheads_benchmark",
    relationship_type: "direct_input",
    notes: "Verified from General Overheads formula: adjusted_general_overheads_benchmark = gross_general_overheads_benchmark - asset_finance_interest_excluded_amount.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.asset_finance_interest_excluded_amount__to__general_overheads.adjusted_general_overheads_benchmark",
    from_node_id: "general_overheads.asset_finance_interest_excluded_amount",
    to_node_id: "general_overheads.adjusted_general_overheads_benchmark",
    relationship_type: "conditional_input",
    notes: "Asset finance exclusion amount is subtracted only where asset finance interest is selected as asset-related and reviewed through the Assets pathway.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.asset_finance_interest_excluded__to__general_overheads.asset_finance_interest_excluded_amount",
    from_node_id: "general_overheads.asset_finance_interest_excluded",
    to_node_id: "general_overheads.asset_finance_interest_excluded_amount",
    relationship_type: "conditional_input",
    notes: "Exclusion amount applies only when the asset finance exclusion flag / review selection is explicit.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.adjusted_general_overheads_benchmark__to__general_overheads.net_general_overheads",
    from_node_id: "general_overheads.adjusted_general_overheads_benchmark",
    to_node_id: "general_overheads.net_general_overheads",
    relationship_type: "direct_input",
    notes: "net_general_overheads is the overhead total after valid exclusions.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.net_general_overheads__to__general_overheads.total_general_overheads",
    from_node_id: "general_overheads.net_general_overheads",
    to_node_id: "general_overheads.total_general_overheads",
    relationship_type: "direct_input",
    notes: "total_general_overheads is the preferred downstream output after valid exclusions and adjustments defined in General Overheads.",
    implementation_status: "verified_in_brief",
  },
  {
    edge_id: "general_overheads.general_overhead_categories__to__general_overheads.total_general_overheads",
    from_node_id: "general_overheads.general_overhead_categories",
    to_node_id: "general_overheads.total_general_overheads",
    relationship_type: "sum_component",
    notes: "Verified from General Overheads formula: total_general_overheads = sum of active general_overhead_categories annual_amount after exclusions and adjustments defined in this module.",
    implementation_status: "verified_in_brief",
  },
];
