export function buildBusinessSummaryHierarchyTrees({
  direct_cost_children,
  margin_after_labour_note,
  people_cost_children,
  pending_contribution_children,
  product_margin_pool_children,
  remaining_cost_children,
  revenue_reference_total,
  scale_suffix,
  scaled_direct_costs,
  scaled_general_overheads,
  scaled_margin_after_labour,
  scaled_margin_pool,
  scaled_net_position,
  scaled_non_people_cost_burden,
  scaled_people_cost,
  scaled_revenue,
  surplus_or_deficit_amount,
  surplus_or_deficit_label,
}) {
  const labour_business_hierarchy = {
    key: "business-result",
    label: "Business Result",
    value: scaled_revenue,
    amount: revenue_reference_total,
    referenceTotal: revenue_reference_total,
    suffix: scale_suffix,
    shareLabel: "revenue",
    note: "This shows how your revenue is consumed before profit is created.",
    children: [
      {
        key: "revenue-generated",
        label: "Revenue Generated",
        value: scaled_revenue,
        amount: revenue_reference_total,
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        isReference: true,
        includeInBar: false,
        note: "This is the income available before direct costs and operating cost baseline are covered.",
      },
      {
        key: "direct-costs",
        label: "COG / Direct Costs",
        value: scaled_direct_costs,
        amount: Math.abs(scaled_direct_costs),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "Direct costs are removed before Gross Profit / Margin Pool is calculated.",
        shareLabel: "direct costs",
        children: direct_cost_children,
      },
      {
        key: "margin-pool",
        label: "Gross Profit / Margin Pool",
        value: scaled_margin_pool,
        amount: Math.abs(scaled_margin_pool),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: false,
        note: "Revenue after COG / Direct Costs.",
        shareLabel: "margin pool",
        children: pending_contribution_children,
      },
      {
        key: "people-cost",
        label: "Less People Cost",
        value: -Math.abs(scaled_people_cost),
        amount: Math.abs(scaled_people_cost),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "People Cost deducted from Gross Profit / Margin Pool.",
        shareLabel: "people cost",
        children: people_cost_children,
      },
      {
        key: "margin-after-labour",
        label: "Margin after Labour",
        value: scaled_margin_after_labour,
        amount: Math.abs(scaled_margin_after_labour),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: false,
        note: margin_after_labour_note.labour,
      },
      {
        key: "remaining-cost-burden",
        label: "Remaining Cost Burden",
        value: scaled_non_people_cost_burden,
        amount: Math.abs(scaled_non_people_cost_burden),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "Asset Cost and Business Overheads still need to be covered after People Cost.",
        shareLabel: "remaining cost burden",
        children: remaining_cost_children,
      },
      {
        key: "surplus-deficit",
        label: surplus_or_deficit_label,
        value: scaled_net_position,
        amount: surplus_or_deficit_amount,
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: scaled_net_position >= 0,
        note:
          scaled_net_position >= 0
            ? "Revenue left after direct costs, People Cost, Asset Cost, and Business Overheads."
            : "Costs exceed revenue by this amount.",
      },
    ],
  };

  const product_business_hierarchy = {
    key: "business-result",
    label: "Business Result",
    value: scaled_revenue,
    amount: revenue_reference_total,
    referenceTotal: revenue_reference_total,
    suffix: scale_suffix,
    shareLabel: "revenue",
    note: "This shows how product revenue becomes trading margin, then whether that margin covers the business cost burden.",
    children: [
      {
        key: "revenue-generated",
        label: "Revenue",
        value: scaled_revenue,
        amount: revenue_reference_total,
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        isReference: true,
        includeInBar: false,
        note: "Product revenue generated before COGS / Direct Costs.",
      },
      {
        key: "direct-costs",
        label: "COGS / Direct Costs",
        value: scaled_direct_costs,
        amount: Math.abs(scaled_direct_costs),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "Direct costs are removed before Trading Margin Pool is calculated.",
        shareLabel: "direct costs",
        children: direct_cost_children,
      },
      {
        key: "margin-pool",
        label: "Trading Margin Pool",
        value: scaled_margin_pool,
        amount: Math.abs(scaled_margin_pool),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: false,
        note: "Revenue after COGS / Direct Costs.",
        shareLabel: "trading margin pool",
        children: product_margin_pool_children,
      },
      {
        key: "people-cost",
        label: "Less People Cost",
        value: -Math.abs(scaled_people_cost),
        amount: Math.abs(scaled_people_cost),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "People Cost deducted from Trading Margin Pool.",
        shareLabel: "people cost",
        children: people_cost_children,
      },
      {
        key: "margin-after-labour",
        label: "Margin after Labour",
        value: scaled_margin_after_labour,
        amount: Math.abs(scaled_margin_after_labour),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: false,
        note: margin_after_labour_note.product,
      },
      {
        key: "remaining-cost-burden",
        label: "Remaining Cost Burden",
        value: scaled_non_people_cost_burden,
        amount: Math.abs(scaled_non_people_cost_burden),
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        note: "Asset Cost and Business Overheads still need to be covered after People Cost.",
        shareLabel: "remaining cost burden",
        children: remaining_cost_children,
      },
      {
        key: "surplus-deficit",
        label: "Final Surplus / Deficit",
        value: scaled_net_position,
        amount: surplus_or_deficit_amount,
        referenceTotal: revenue_reference_total,
        suffix: scale_suffix,
        includeInBar: scaled_net_position >= 0,
        note: "Final position after Trading Margin Pool is reduced by People Cost, Asset Cost, and Business Overheads.",
      },
    ],
  };

  return {
    labour_business_hierarchy,
    product_business_hierarchy,
  };
}
